apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yi1tv4v4g-dotnet-basic
  janus-idp.io/tekton: yi1tv4v4g-dotnet-basic
  backstage.io/kubernetes-id: yi1tv4v4g-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yi1tv4v4g-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
